### ISSUE TITLE
Inline configuration

### ISSUE THREAD

**Issue by andrewPoland** [arkiaconsulting/vsts-terraform#1]
It would be great if there was the option to provide inline terraform variables rather than only from a `tfvars` file. 

My reasoning is that I want to keep all my projects configuraiton inside a single location, or when provided by external resources accessible from that location. Currently that location is VSTS for me so I'm trying to avoid committing configuration into source control. 

I've created a work around by using powershell to generate the `tfvars` file from my VSTS configuration before calling the extension. It would be nicer if I could add these through your extension though.

Ideally choosing between varsfile or inline. If there's a way to do a incresable key-value pair input that would be cool otherwise just a single input which gets injected into the command. 

![image](https://user-images.githubusercontent.com/3516868/43048342-062ba6e2-8d9b-11e8-9468-e01ba6056f08.png)

results in

<pre><code>$ terraform plan <b>-var foo=bar -var foz=baz</b></code></pre>

work around I'm using below in case others want to do the same.

I named all my variables in VSTS with format

`Terraform.<input variable name>`

the script depends on this when finding the variables to add to the `tfvars` file

```
# get terraform based environment variables I've defined in VSTS. (Change -like to match your pattern.)

$var = (gci env:*).GetEnumerator() | where {$_.Name -like “TERRAFORM_*”}  |  Sort-Object Name
$out = ""

# create file content. (Change .Replace to match your pattern)

Foreach ($v in $var) {$out = $out + "`t{0,-28} = {1,-28}`n" -f $v.Name.Replace("TERRAFORM_", "").ToLower(), $v.Value}

# save file. filename must match what's in the extension configuration.
$fileName = "$env:SYSTEM_DEFAULTWORKINGDIRECTORY\Drop\drop\configuration.tfvars"
set-content $fileName $out

```

**Comment by arkiaman** [comment]
I won't fix in the current version of the task.
As a side note, I'm currently developing a new version of the extension, which will consist in a set of terraform tasks. A single task to rule them all was becoming too messy.
