### ISSUE TITLE
Multiple outputs

### ISSUE THREAD

**Issue by andrewPoland** [arkiaconsulting/vsts-terraform#2]
I'm attempting to get 2 outputs from terraform. Is this possible with your extension? 

![image](https://user-images.githubusercontent.com/3516868/43048445-74342fa0-8d9c-11e8-9290-c1f7e2ad0cb0.png)

The language used indicates that it only allows for a single output. Is there any syntax I can use to allow multiple?

The outputs.tf I'm using is below.

```
output "topic_connection_string" {
  sensitive = true
  value = "${module.service_bus.topic_connection_string}"
}

output "application_insights_instrumentation_key" {
  sensitive = true
  value = "${module.application_insights.instrumentation_key}"
}
```

**Comment by andrewPoland** [comment]
https://github.com/arkiaconsulting/vsts-terraform/blob/48d8543f7cbc2085ef3ea010209b077f4e8ad22f/terraform/src/terraformCommandBuilder.ts#L237-L247

After looking at code it looks like the above is used which means only a single value is currently supported. A quick way to provide this feature would be to make `outputName` optional. This would cause it to execute. 

`terraform.exe output -json` 

which will output all variables in json. I think this would still require addressing issue #3

**Comment by arkiaman** [comment]
I won't fix in the current version of the task.
As a side note, I'm currently developing a new version of the extension, which will consist in a set of terraform tasks. A single task to rule them all was becoming too messy.
