### ISSUE TITLE
Node 6 execution handler will be deprecated soon in Microsoft Hostest Azure DevOps agents

### ISSUE THREAD

**Issue by orecht** [arkiaconsulting/vsts-terraform#24]
When running an Azure DevOps build on Microsoft Hosted Agents, I get the following message: 

`##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.`

The pipeline is using `ubuntu-latest` agents

Is it possible to upgrade the task to Node 10 handler?

**Comment by arkiaman** [comment]
@orecht This task is no longer maintained. It was created when no Microsoft/Hashicorp task was available for Vsts.

You should now use those tasks.
