### ISSUE TITLE
outputs of type map cause errors when assigning VSTS task variable

### ISSUE THREAD

**Issue by andrewPoland** [arkiaconsulting/vsts-terraform#3]
I'm trying to output all variables by using a map.  

outputs.tf 
```
output "all_for_one" {
  value = "${
    map(
      "topic_connection_string", "${module.service_bus.topic_connection_string}",
      "application_insights_instrumentation_key", "${module.application_insights.instrumentation_key}"
    )
  }"
}
```

results in the following logs in VSTS. 

![image](https://user-images.githubusercontent.com/3516868/43050355-2d55c182-8dbc-11e8-950f-6cc3ad465be5.png)

I think this is because of the following. 

https://github.com/arkiaconsulting/vsts-terraform/blob/48d8543f7cbc2085ef3ea010209b077f4e8ad22f/terraform/src/terraformCommandBuilder.ts#L244-L246

since output.value is an object SetTaskVariable can't handle it. I think if you removed the `JSON.parse` it should assign the string to the variable. For normal values that will just be an ordinary string but for maps it will be json, key-values which can be processed in subsequent steps.

**Comment by arkiaman** [comment]
I won't fix in the current version of the task.
As a side note, I'm currently developing a new version of the extension, which will consist in a set of terraform tasks. A single task to rule them all was becoming too messy.
In the new version, you will have a single output task to fetch multiple terraform outputs.
