### ISSUE TITLE
Secret outputs printed to logs. 

### ISSUE THREAD

**Issue by andrewPoland** [arkiaconsulting/vsts-terraform#4]
output of `terraform.exe ouput` is getting printed to stdout which gets persisted in VSTS logs. 

with an output.tf 
```
output "topic_connection_string" {
  sensitive = true
  value = "${module.service_bus.topic_connection_string}"
}
```
![image](https://user-images.githubusercontent.com/3516868/43050581-5a0b2100-8dc0-11e8-90e4-622ec9b91852.png)

**Comment by arkiaman** [comment]
Sorry for late reply. This is fixed now. The task inspects the sensitive property of the terraform output, and in case it is, it saves the Azure Pipeline variable as secret.
