### ISSUE TITLE
Can't read VSTS variable from output in subsequent tasks

### ISSUE THREAD

**Issue by andrewPoland** [arkiaconsulting/vsts-terraform#5]
I have vsts-terraform setup as follows. 

![image](https://user-images.githubusercontent.com/3516868/43051477-7af594e0-8dcf-11e8-9889-035dfb994894.png)

My understanding is I should then be able to access the variable via

`$(UserOutput)` or  `$env:UserOutput` in powershell.

Looking at the code I found you call SetTaskVariable within vsts-task-lib. My understanding is this makes the variable only accessible within the vsts-terraform task. In order to use it in other tasks SetVariable should be used.  

https://stackoverflow.com/a/45606355

![image](https://user-images.githubusercontent.com/3516868/43051535-4860ef88-8dd0-11e8-970d-9e1ddf858dbe.png)

**Comment by arkiaman** [comment]
I won't fix in the current version of the task.
As a side note, I'm currently developing a new version of the extension, which will consist in a set of terraform tasks. A single task to rule them all was becoming too messy.
